var ARTICLES = [
  {
    id: "cleopatra",
    title: "Cleopatra VII: The Last Pharaoh",
    subtitle: "She spoke nine languages, commanded armies, and made two of the most powerful men in the world fall completely apart. And she did it all before 39.",
    category: "Ancient Egypt",
    date: "69 BCE - 30 BCE",
    readTime: "12 min read",
    symbol: "\u2640",
    tags: ["Egypt","Female","Royalty","Politics"],
    intro: "Let us be honest about something. When most people hear the name Cleopatra, they picture Elizabeth Taylor in heavy eyeliner. That is not Cleopatra. That is Hollywood. The real Cleopatra was something far more interesting, far more dangerous, and frankly, far more impressive than any film has ever managed to capture.",
    body: [
      { type:"heading", text:"Who Was She, Really?" },
      { type:"para", text:"Cleopatra VII Philopator was born in 69 BCE in Alexandria, Egypt. She was the daughter of Ptolemy XII, a king so desperate to keep his throne that he literally paid the Romans to protect him. Her family, the Ptolemaic dynasty, had ruled Egypt for nearly three hundred years at that point, and here is the remarkable thing: not one of them had ever bothered to learn Egyptian. They ruled Egypt for three centuries and could not speak to their own people." },
      { type:"para", text:"Cleopatra changed that. She learned Egyptian. She also learned Ethiopian, Hebrew, Aramaic, Arabic, Parthian, Median, and Latin. Nine languages total. She did not do this because she was bored. She did it because she understood something her ancestors never did: if you want people to follow you, you have to speak to them in their own tongue. Literally and figuratively." },
      { type:"quote", text:"She was a woman of surpassing beauty, and at that time, when she was in the prime of her youth, she was most striking. She also possessed a most charming voice and knowledge of how to make herself agreeable to everyone.", author:"Cassius Dio, Roman Historian" },
      { type:"heading", text:"The Throne Was Not Given to Her" },
      { type:"para", text:"When her father died in 51 BCE, Cleopatra was eighteen years old. She was supposed to rule jointly with her ten-year-old brother, Ptolemy XIII. Now, ruling jointly with a ten-year-old sounds manageable. Except that ten-year-old had advisors, and those advisors had ambitions, and within three years they had driven Cleopatra out of Egypt entirely." },
      { type:"para", text:"She did not sit in exile and cry about it. She raised an army. She camped on the border of Egypt with soldiers she had recruited herself, waiting for the right moment. That moment came in the form of Julius Caesar, who arrived in Alexandria in 48 BCE chasing his rival Pompey." },
      { type:"para", text:"What happened next is one of the most audacious moves in political history. Cleopatra needed to meet Caesar without her brother's guards killing her first. So she had herself rolled up inside a carpet, or possibly a linen sack depending on which ancient source you trust, and smuggled into the palace. She was unrolled in front of Julius Caesar, the most powerful man in the world, and apparently made such an impression that by morning they were allies. And more than allies." },
      { type:"highlight", text:"She did not wait to be rescued. She smuggled herself into the room where the decisions were being made." },
      { type:"heading", text:"Caesar, Antony, and the Art of Strategic Partnership" },
      { type:"para", text:"Here is where history gets complicated, and where people often get Cleopatra wrong. Her relationships with Julius Caesar and later Mark Antony were not simply romantic. They were political alliances of the highest order. Cleopatra needed Roman military power to secure her throne. Caesar and Antony needed Egyptian wealth and grain to fund their ambitions. It was a partnership between equals who happened to also genuinely care for each other." },
      { type:"para", text:"With Caesar's backing, Cleopatra defeated her brother in a civil war. Ptolemy XIII drowned in the Nile trying to flee. She then ruled Egypt for the next two decades, overseeing a period of genuine prosperity. She managed the economy, maintained the temples, kept the grain supply stable, and expanded Egyptian trade networks. She was, by any measure, a competent and effective ruler." },
      { type:"para", text:"When Caesar was assassinated in 44 BCE, Cleopatra was in Rome with their son Caesarion. She returned to Egypt, had her remaining brother poisoned, and continued ruling. She was twenty-five years old and had already survived more political crises than most rulers face in a lifetime." },
      { type:"quote", text:"Age cannot wither her, nor custom stale her infinite variety.", author:"Shakespeare, Antony and Cleopatra" },
      { type:"heading", text:"The End, and Why It Matters" },
      { type:"para", text:"Her alliance with Mark Antony ultimately failed. Octavian, who would become Augustus Caesar, defeated them at the Battle of Actium in 31 BCE. Antony died believing Cleopatra had already killed herself. Cleopatra, captured and facing the humiliation of being paraded through Rome as a trophy, chose death on her own terms." },
      { type:"para", text:"The asp story, that she pressed a venomous snake to her breast, is probably not accurate. Most historians now believe she used a poison. But the point is not the method. The point is the choice. She refused to be someone else's spectacle. She had ruled the most powerful kingdom in the ancient world for twenty-one years. She was not going to end as a prop in someone else's triumph." },
      { type:"para", text:"She was thirty-nine years old." },
      { type:"highlight", text:"She was the last active ruler of the Ptolemaic Kingdom of Egypt. After her death, Egypt became a Roman province and would not be independent again for nearly two thousand years." },
      { type:"heading", text:"What We Can Learn From Her" },
      { type:"para", text:"Cleopatra was not perfect. She had people killed when it served her interests. She made strategic errors. She bet on the wrong Roman at the end. But she also built something real. She ruled with intelligence, adaptability, and a genuine connection to her people that her ancestors never managed." },
      { type:"para", text:"The lesson is not that she was a romantic figure. The lesson is that she was a professional. She studied, she prepared, she adapted, and she never stopped fighting for what she believed was hers. In a world that gave women almost no formal power, she held the most powerful throne on earth for two decades." },
      { type:"para", text:"That is not a love story. That is a masterclass." }
    ]
  },
  {
    id: "gilgamesh-doc",
    title: "Gilgamesh: The King Who Was Afraid to Die",
    subtitle: "He was two-thirds god, one-third man, and one hundred percent terrified of the one thing no amount of divine blood could protect him from.",
    category: "Ancient Mesopotamia",
    date: "Circa 2700 BCE",
    readTime: "10 min read",
    symbol: "\u2605",
    tags: ["Mesopotamia","Male","King","Epic"],
    intro: "The oldest story ever written is not about love, or war, or the creation of the world. It is about a man who watched his best friend die and could not handle it. That is the Epic of Gilgamesh. Written on clay tablets in ancient Sumer over four thousand years ago, it is the first great work of human literature, and it is about grief.",
    body: [
      { type:"heading", text:"The King of Uruk" },
      { type:"para", text:"Gilgamesh was the king of Uruk, one of the first great cities in human history, located in what is now southern Iraq. According to the epic, he was two-thirds divine and one-third human, which sounds impressive until you realize that the one-third human part was the part that was going to die, and there was nothing the other two-thirds could do about it." },
      { type:"para", text:"He was, by all accounts, a difficult king. The epic opens with the people of Uruk complaining to the gods about him. He was too strong, too energetic, too much. He exhausted his warriors with constant training and competition. He claimed the right to sleep with every new bride before her husband. The gods, listening to these complaints, decided the best solution was to create someone who could match him." },
      { type:"quote", text:"He was the first to dig wells in the mountains. He crossed the ocean, the vast sea, to the sunrise. He explored the world regions, seeking life.", author:"The Epic of Gilgamesh, Tablet I" },
      { type:"heading", text:"Enkidu: The Friend Who Changed Everything" },
      { type:"para", text:"The gods created Enkidu from clay and wild nature. He lived among animals, ate grass, and knew nothing of human civilization. A hunter spotted him and, on advice, sent a woman named Shamhat to civilize him. She spent six days and seven nights with Enkidu, and when it was over, the animals no longer recognized him. He had become human." },
      { type:"para", text:"Enkidu came to Uruk to challenge Gilgamesh. They fought in the street, a battle so intense it shook the walls of the city. Neither could defeat the other. They stopped, looked at each other, and became the closest of friends. This is how the ancient world understood friendship: you find the one person who can match you, and you never let them go." },
      { type:"highlight", text:"They were so alike that the gods grew nervous. Two men that powerful, that bonded, were a force that heaven itself could not easily control." },
      { type:"heading", text:"The Death That Broke Him" },
      { type:"para", text:"Together, Gilgamesh and Enkidu killed the monster Humbaba in the Cedar Forest and slew the Bull of Heaven sent by the goddess Ishtar after Gilgamesh rejected her romantic advances. Rejecting a goddess is, historically speaking, a poor life choice. The gods convened and decided that one of the two friends had to die as punishment. They chose Enkidu." },
      { type:"para", text:"Enkidu fell ill and died over twelve days. Gilgamesh sat beside him and refused to accept it. He kept vigil over the body for seven days and seven nights, until a maggot fell from Enkidu's nose and he finally understood that his friend was truly gone." },
      { type:"para", text:"What happened next is the heart of the story. Gilgamesh, the greatest warrior in the world, the man who had killed monsters and defied gods, fell apart. He tore off his royal robes. He let his hair grow wild. He wandered into the wilderness wearing only a lion skin, weeping, asking everyone he met the same question: how do I avoid dying?" },
      { type:"quote", text:"When I die, shall I not be like Enkidu? Sorrow has entered my heart. I am afraid of death.", author:"Gilgamesh, Tablet IX" },
      { type:"heading", text:"The Search for Immortality" },
      { type:"para", text:"He traveled to the ends of the earth. He crossed the Waters of Death. He found Utnapishtim, the only human ever granted immortality by the gods, the man who had survived the great flood by building a boat. Sound familiar? The Epic of Gilgamesh contains a flood narrative remarkably similar to Noah's Ark, written at least a thousand years before the Book of Genesis." },
      { type:"para", text:"Utnapishtim told Gilgamesh that immortality was not something that could be given. But he offered a test: stay awake for seven days and seven nights. Gilgamesh sat down to try and fell asleep almost immediately. He slept for seven days. Utnapishtim's wife baked a loaf of bread each day he slept, so when he woke up and denied it, there were seven loaves in various states of decay as evidence." },
      { type:"para", text:"As a consolation, Utnapishtim told him about a plant at the bottom of the ocean that could restore youth. Gilgamesh dove to the bottom, retrieved the plant, and began the journey home. He stopped to bathe in a cool pool. A serpent smelled the plant, came out of the water, and ate it. The serpent shed its skin and slithered away. Gilgamesh sat on the bank and wept." },
      { type:"highlight", text:"He had traveled to the ends of the earth, crossed death itself, and a snake ate his prize while he was taking a bath. Ancient literature understood irony." },
      { type:"heading", text:"What He Found Instead" },
      { type:"para", text:"Gilgamesh returned to Uruk empty-handed. But the epic ends with him standing at the walls of his city, looking at what he had built. The walls of Uruk were famous throughout the ancient world. They were his legacy. The story suggests that this is what he had been looking for all along, not immortality of the body, but immortality of the deed." },
      { type:"para", text:"The Epic of Gilgamesh is four thousand years old and it is still being read. Gilgamesh got his immortality after all. He just did not get to enjoy it." },
      { type:"para", text:"The story resonates because it is honest about something we all know but rarely say out loud: we are all afraid of dying, and most of us spend our lives looking for the plant at the bottom of the ocean, only to have a snake eat it while we are not paying attention. The question is what we build while we are searching." }
    ]
  },
  {
    id: "mulan-hua",
    title: "Hua Mulan: The Woman Who Fooled an Army for Twelve Years",
    subtitle: "She took her father's place in the imperial army, fought for over a decade, rose to the rank of general, and then went home to do her hair. The men she served with had no idea.",
    category: "Ancient China",
    date: "Circa 400 CE",
    readTime: "9 min read",
    symbol: "\u5973",
    tags: ["China","Female","Warrior","Legend"],
    intro: "The story of Hua Mulan is one of the most enduring legends in Chinese history. It has been told for over fifteen hundred years, turned into a poem, a play, an opera, and yes, eventually a Disney film that takes considerable creative liberties. But the core of the story, a young woman who disguised herself as a man to serve in the army in her elderly father's place, has survived all those retellings because it speaks to something true about courage, loyalty, and the absurdity of telling half the population they are not allowed to fight.",
    body: [
      { type:"heading", text:"The Ballad of Mulan" },
      { type:"para", text:"The earliest known version of Mulan's story is the Ballad of Mulan, a poem written sometime during the Northern Wei dynasty, around 400 to 500 CE. It is a short poem, only about three hundred words in the original Chinese, but it contains everything: the aging father, the draft notice, the decision, the disguise, the years of service, the return home, and the reveal." },
      { type:"para", text:"The poem opens with Mulan weaving at her loom, sighing. Her father has received a draft notice. The emperor is at war and every family must send a soldier. Mulan's father is old and ill. Her brother is too young. There is no one else. So Mulan goes to the market, buys a horse, a saddle, a bridle, and a whip, and rides off to war in her father's place." },
      { type:"quote", text:"Father and mother heard her go, they called to her through the night. But she could not hear them, for she was already far away, crossing the Yellow River.", author:"Ballad of Mulan, Northern Wei Dynasty" },
      { type:"heading", text:"Twelve Years in the Field" },
      { type:"para", text:"The poem is deliberately vague about the details of her military service, which is either a poetic choice or a practical one, since explaining how a woman fooled an entire army for twelve years would require a great deal of explanation. What the poem tells us is that she fought in a hundred battles, crossed mountains and rivers, survived freezing nights and burning days, and rose to a position of significant honor." },
      { type:"para", text:"The later, expanded versions of the story are more specific. They describe her as a brilliant tactician who won battles through strategy rather than brute force. She learned to read terrain, to use weather as a weapon, to move troops in ways her enemies did not expect. She became a general. The emperor himself offered her a high government position when the war ended." },
      { type:"highlight", text:"She turned down the emperor's offer of a government position. She asked only to go home. In ancient China, turning down the emperor was not something people did lightly. She did it anyway." },
      { type:"heading", text:"The Return" },
      { type:"para", text:"When Mulan finally returned home, she went to her room, changed back into women's clothing, did her hair, and came back out. Her fellow soldiers, who had fought beside her for twelve years, were stunned. The poem records their reaction with what can only be described as ancient Chinese deadpan humor: 'We traveled together for twelve years and did not know Mulan was a girl.'" },
      { type:"para", text:"This is the moment the story has always been building toward, not the battles, not the victories, but this. Twelve years. They had eaten together, slept in the same camps, fought in the same formations, trusted each other with their lives, and not one of them had known. The poem does not treat this as a scandal. It treats it as a marvel." },
      { type:"quote", text:"The male rabbit kicks his legs, the female rabbit has misty eyes. But when two rabbits run side by side, who can tell which is male and which is female?", author:"Ballad of Mulan, closing lines" },
      { type:"heading", text:"What the Story Is Actually About" },
      { type:"para", text:"The closing lines of the Ballad of Mulan are the key to understanding why this story has lasted fifteen hundred years. The rabbit metaphor is not subtle. When rabbits are running, you cannot tell the difference between male and female. The poem is asking, directly and without apology: if a woman can do everything a man can do, why are we pretending otherwise?" },
      { type:"para", text:"This question was radical in 400 CE. It is still being asked today. The story of Mulan has survived because it refuses to answer the question for you. It just shows you a woman who fought for twelve years, won, came home, and went back to her life. And then it asks: so what exactly was the problem?" },
      { type:"para", text:"The Disney version adds a love interest and a dragon. The original poem has neither. It has something better: a woman who did what needed to be done, asked for nothing in return, and went home to her family. That is the whole story. That is enough." }
    ]
  },
  {
    id: "leonidas",
    title: "Leonidas: The King Who Chose the Pass",
    subtitle: "He took three hundred men to hold a narrow pass against an army of hundreds of thousands. He knew he was not coming back. He went anyway.",
    category: "Ancient Greece",
    date: "480 BCE",
    readTime: "11 min read",
    symbol: "\u03bb",
    tags: ["Greece","Male","Warrior","King"],
    intro: "The Battle of Thermopylae is one of the most famous military engagements in human history, and it was a defeat. The Spartans lost. Leonidas died. The pass fell. And yet, two and a half thousand years later, people are still talking about it. That tells you something important about what we value, and what we remember, and why sometimes the way you lose matters more than whether you win.",
    body: [
      { type:"heading", text:"Sparta Was Not What You Think" },
      { type:"para", text:"Before we talk about Leonidas, we need to talk about Sparta, because the popular image of Sparta, all abs and slow-motion battle scenes, is about forty percent accurate and sixty percent Hollywood. Yes, Spartan warriors were extraordinarily well trained. Yes, the military culture was intense to a degree that would be considered child abuse by modern standards. But Sparta was also a society with a complex political system, a tradition of female education and property rights unusual for the ancient world, and a genuine philosophical tradition around the concept of duty." },
      { type:"para", text:"Leonidas became king of Sparta around 490 BCE. He was not the first in line for the throne. He became king because his older brothers died. He was, by all accounts, a thoughtful and experienced military commander who had spent his entire life training for exactly the kind of situation he would face at Thermopylae." },
      { type:"heading", text:"Xerxes and the Invasion" },
      { type:"para", text:"In 480 BCE, the Persian king Xerxes assembled what ancient sources describe as an army of two million men. Modern historians think the real number was somewhere between 100,000 and 300,000, which is still an almost incomprehensible force for the ancient world. Xerxes was not just invading Greece. He was making a statement. His father Darius had been defeated at Marathon ten years earlier. Xerxes was going to finish the job." },
      { type:"para", text:"The Greek city-states, which spent most of their time fighting each other, managed to form a coalition. They needed to slow the Persian advance long enough to prepare a naval defense. Someone had to hold a chokepoint. The chokepoint they chose was Thermopylae, a narrow coastal pass where the mountains met the sea, wide enough in places for only a few men to stand abreast." },
      { type:"quote", text:"Go tell the Spartans, stranger passing by, that here, obedient to their laws, we lie.", author:"Simonides, epitaph at Thermopylae" },
      { type:"heading", text:"The Three Hundred" },
      { type:"para", text:"Leonidas brought three hundred Spartan warriors to Thermopylae. He also brought several thousand allied Greek soldiers, which the popular telling often forgets. The Thespians in particular, seven hundred men who knew their city would be destroyed if the Persians broke through, fought to the last man alongside the Spartans. They deserve to be remembered." },
      { type:"para", text:"For two days, the Greeks held the pass. The Persian army, despite its overwhelming numbers, could not bring that advantage to bear in the narrow space. Wave after wave of Persian soldiers broke against the Spartan formation. Xerxes reportedly watched from a throne on a nearby hill and rose to his feet three times in alarm as his men were cut down." },
      { type:"highlight", text:"When a Persian messenger told Leonidas that their arrows would blot out the sun, a Spartan soldier named Dieneces reportedly replied: 'Good. Then we shall fight in the shade.' This may be the greatest one-liner in military history." },
      { type:"heading", text:"The Betrayal" },
      { type:"para", text:"On the third day, a local man named Ephialtes told Xerxes about a mountain path that went around the pass. Xerxes sent his elite troops, the Immortals, along this path overnight. When Leonidas learned that his position was about to be surrounded, he sent most of the allied forces away. He kept the three hundred Spartans, the seven hundred Thespians, and a few hundred Thebans." },
      { type:"para", text:"Why did he stay? The oracle at Delphi had told the Spartans that either Sparta would be destroyed or a Spartan king would die. Leonidas understood what was required. He also understood that a fighting retreat, with the Persians now coming from both directions, would give the rest of the Greek forces time to escape." },
      { type:"para", text:"He moved his men out of the pass and into a wider area, where they could at least die fighting rather than be shot down from a distance. They fought until their spears broke, then with swords, then with hands and teeth according to Herodotus. Leonidas was killed early in the final battle. His men fought over his body to prevent the Persians from taking it." },
      { type:"heading", text:"Why It Mattered" },
      { type:"para", text:"The Persian army took three days to get through a pass that should have taken hours. That delay allowed the Greek fleet to prepare. The naval battle of Salamis, fought shortly after, destroyed the Persian fleet and effectively ended the invasion. Greece survived. Western civilization, for whatever that phrase is worth, continued on a different path than it would have if Persia had won." },
      { type:"para", text:"Leonidas did not save Greece by himself. But he bought the time that made saving Greece possible. He knew what he was doing. He chose it. That is what people remember, not the tactics, not the numbers, but the choice." },
      { type:"quote", text:"Come and take them.", author:"Leonidas, when Xerxes demanded the Spartans lay down their weapons" }
    ]
  },
  {
    id: "nefertiti",
    title: "Nefertiti: The Queen Who May Have Been Pharaoh",
    subtitle: "Her bust is one of the most recognized faces in the ancient world. Her actual story is so much stranger and more powerful than the pretty picture.",
    category: "Ancient Egypt",
    date: "Circa 1370 BCE - 1330 BCE",
    readTime: "10 min read",
    symbol: "\u2640",
    tags: ["Egypt","Female","Royalty","Mystery"],
    intro: "Nefertiti is famous for her face. The painted limestone bust discovered in 1912 and now housed in Berlin is one of the most reproduced images from the ancient world. She has been on magazine covers, inspired fashion collections, and been cited as a standard of beauty for over a century. But here is the thing about Nefertiti: we barely know anything about her, and what we do know suggests she was far more than a pretty face. She may have ruled Egypt as pharaoh. And then she vanished.",
    body: [
      { type:"heading", text:"The Wife of the Heretic King" },
      { type:"para", text:"Nefertiti was the Great Royal Wife of Pharaoh Akhenaten, one of the most controversial rulers in Egyptian history. Akhenaten did something that no Egyptian pharaoh had ever done: he abolished the traditional Egyptian pantheon of gods and replaced them all with a single deity, the Aten, represented as the sun disk. He moved the capital to a new city he built from scratch, called Akhetaten, modern day Amarna. He rewrote the religious, artistic, and political structure of the most stable civilization on earth." },
      { type:"para", text:"This was, to put it mildly, not popular. The priests of Amun, who had accumulated enormous wealth and power over centuries, suddenly found themselves out of a job. The traditional temples were closed. The old gods were erased from monuments. Egypt, which had maintained the same basic religious structure for over a thousand years, was turned upside down in the space of a few years." },
      { type:"quote", text:"Beautiful are the beauties of Aten, the great living Aten. Nefertiti, Lady of Grace, sweet of love.", author:"Hymn to the Aten, Amarna Period" },
      { type:"heading", text:"More Than a Consort" },
      { type:"para", text:"In the art of the Amarna period, Nefertiti appears in a role unprecedented for an Egyptian queen. She is shown smiting enemies, a pose traditionally reserved for pharaohs. She wears the double crown of Egypt. She officiates at religious ceremonies alongside Akhenaten as an equal, not as a supporting figure. Some images show her alone, performing rituals that only a pharaoh was supposed to perform." },
      { type:"para", text:"Egyptologists have debated for decades what this means. The most conservative interpretation is that it was symbolic, that she was elevated in imagery to reflect her importance as the mother of the royal children. She had six daughters with Akhenaten. The more radical interpretation, supported by a growing body of evidence, is that she was genuinely co-ruler of Egypt, with real political and religious authority." },
      { type:"highlight", text:"She had six daughters and no sons. In a culture that valued male heirs above almost everything else, she remained Great Royal Wife and apparently co-ruler for her entire marriage. That is not nothing. That is extraordinary." },
      { type:"heading", text:"The Disappearance" },
      { type:"para", text:"Around year twelve of Akhenaten's reign, Nefertiti disappears from the historical record. No tomb has ever been definitively identified as hers. No death record. No mention in later texts. She simply stops appearing in the documents and monuments that had featured her so prominently for over a decade." },
      { type:"para", text:"Three theories have dominated the scholarly debate. The first is that she died, possibly in the plague that swept through Egypt around that time. The second is that she fell from favor, perhaps due to a political dispute with Akhenaten. The third, and most intriguing, is that she did not disappear at all. She changed her name." },
      { type:"para", text:"Shortly after Nefertiti vanishes from the record, a figure called Neferneferuaten appears as co-regent with Akhenaten. This person is referred to with feminine grammatical forms in some texts. After Akhenaten's death, a pharaoh called Smenkhkare ruled briefly before the famous Tutankhamun took the throne. Some Egyptologists believe Nefertiti, Neferneferuaten, and Smenkhkare may all be the same person." },
      { type:"heading", text:"The Search for Her Tomb" },
      { type:"para", text:"In 2015, British Egyptologist Nicholas Reeves proposed that Nefertiti's tomb might be hidden behind a concealed doorway in the tomb of Tutankhamun in the Valley of the Kings. Radar scans suggested the presence of a void behind the north wall of Tutankhamun's burial chamber. The theory caused enormous excitement in the archaeological world." },
      { type:"para", text:"Subsequent investigations have been inconclusive. The Egyptian government has been cautious about allowing invasive testing. The question remains open. Somewhere in Egypt, almost certainly, lies the tomb of one of the most powerful women in the ancient world. We have not found it yet." },
      { type:"quote", text:"The heiress, great in the palace, fair of face, adorned with the double plumes, mistress of happiness.", author:"Inscription at Amarna, describing Nefertiti" },
      { type:"heading", text:"What Her Story Tells Us" },
      { type:"para", text:"Nefertiti's story is a reminder that history is full of gaps, and that the gaps are not random. They tend to fall around women, around people who challenged the established order, around those whose stories were inconvenient for whoever came next. After Akhenaten's death, his successors worked systematically to erase the Amarna period from Egyptian history. Temples were demolished. Names were chiseled off monuments. The city of Akhetaten was abandoned and eventually buried by sand." },
      { type:"para", text:"Nefertiti survived that erasure because her bust was buried in a sculptor's workshop and forgotten for three thousand years. Her face survived by accident. Her story survived because people kept asking questions. That is how most of history works. The official record is what the powerful wanted remembered. The real story is what survives in spite of them." }
    ]
  }
];