// ===== ALL SITE DATA =====

var STORIES = [
  { id:"ryugu", title:"The Dragon of Ryugu", category:"japanese", symbol:"\u40845", badge:"Japanese Mythology", short:"A fisherman is carried beneath the ocean to the Dragon Palace, where time moves differently.", text:"<p>Long ago, a fisherman named Urashima Taro rescued a sea turtle on the shore. In gratitude, the turtle carried him beneath the waves to Ryugu-jo, the Dragon Palace at the bottom of the ocean.</p><p>There he was welcomed by Otohime, the Dragon King's daughter, and spent what felt like three blissful days in the palace of wonders. But when he returned to the surface, three hundred years had passed.</p><p>His village was gone. His family was dust. He opened the box Otohime had given him, despite her warning never to do so, and in an instant he aged three hundred years and crumbled to nothing.</p><p><em>Some doors, once opened, cannot be closed. Some gifts are warnings in disguise.</em></p>" },
  { id:"prometheus", title:"Prometheus Unchained", category:"greek", symbol:"\u26a1", badge:"Greek Mythology", short:"A Titan steals fire from the gods and gives it to mankind, paying an eternal price.", text:"<p>Before fire, mankind shivered in the dark. The gods of Olympus kept warmth for themselves, watching mortals suffer from their golden thrones.</p><p>Prometheus, the Titan who loved humanity more than he feared Zeus, climbed to the sun and stole a spark. He carried it down in a hollow fennel stalk and gave it to the people of earth.</p><p>Zeus was furious. He chained Prometheus to a mountain in the Caucasus, where every day an eagle would come and eat his liver. Every night it would grow back. Every day the eagle would return.</p><p>For thousands of years he endured, until Heracles finally broke his chains. But Prometheus never regretted it. Not once.</p><p><em>The price of love is often suffering. Pay it anyway.</em></p>" },
  { id:"ragnarok", title:"Ragnarok: The Final Battle", category:"norse", symbol:"\u2694", badge:"Norse Mythology", short:"The twilight of the gods. When Fenrir breaks free, even Odin cannot escape fate.", text:"<p>The signs came slowly. Fimbulwinter, three years of endless cold. Brother turned against brother. The wolf Fenrir broke his chains. The Midgard Serpent rose from the ocean, poisoning the sky.</p><p>Odin rode out on Sleipnir, knowing he would not return. Thor swung Mjolnir one last time. Freyr fought without his sword, which he had given away for love.</p><p>The gods fell. The world burned. The sea swallowed the land.</p><p>But then, from the waters, a new earth rose. Green and clean. Two humans had survived, hidden in the world tree. The cycle began again.</p><p><em>Even the end of everything is not truly the end.</em></p>" },
  { id:"monkeyking", title:"The Monkey King", category:"chinese", symbol:"\u732b", badge:"Chinese Mythology", short:"Born from stone, Sun Wukong defied heaven itself on a journey from chaos to enlightenment.", text:"<p>Sun Wukong was born from a stone egg on the Mountain of Flowers and Fruit. He learned the 72 transformations, stole the Dragon King's staff, and declared himself equal to heaven itself.</p><p>The Jade Emperor tried to contain him. Sun Wukong ate the peaches of immortality, drank the elixir of the gods, and could not be killed by any weapon in heaven or earth.</p><p>It took the Buddha himself to trap him beneath a mountain for five hundred years. When he was finally freed, it was to escort the monk Xuanzang on a journey to the west to retrieve sacred scriptures.</p><p>Through 81 trials, he fought demons, protected his master, and slowly became something greater than a god. He became wise.</p><p><em>The wildest spirit, when given purpose, becomes the greatest protector.</em></p>" },
  { id:"osiris", title:"Osiris and the Underworld", category:"egyptian", symbol:"\u2625", badge:"Egyptian Mythology", short:"Betrayed by his brother Set, Osiris was scattered across the earth and reassembled by love.", text:"<p>Osiris was the good king of Egypt, beloved by all. His brother Set burned with jealousy. He tricked Osiris into lying in a golden coffin, sealed it shut, and threw it into the Nile.</p><p>His wife Isis searched the entire world for him. She found the coffin, brought it home, and breathed life back into him long enough to conceive their son Horus.</p><p>Set found the body again and cut it into fourteen pieces, scattering them across Egypt. Isis gathered every piece and reassembled her husband. He became the ruler of the dead, the judge of souls, the god of resurrection.</p><p><em>Love does not accept death as a final answer.</em></p>" },
  { id:"oni", title:"The Oni of Mount Oe", category:"japanese", symbol:"\u9b3c", badge:"Japanese Mythology", short:"A demon lord ruled from a mountain peak until a warrior climbed to face him.", text:"<p>On the peak of Mount Oe, the demon lord Shuten-doji ruled with his army of Oni. He kidnapped nobles from the capital and feasted on their flesh and blood, and no warrior dared face him.</p><p>The warrior Minamoto no Raiko disguised himself and his men as traveling monks. They climbed the mountain, accepted the demon's hospitality, and drank with him through the night.</p><p>Shuten-doji, drunk on sake laced with a divine potion, fell into a deep sleep. Raiko drew his blade and struck. Even as his head was severed, the demon's jaws snapped shut, trying to bite his killer one last time.</p><p><em>Even the mightiest fall when pride blinds them to danger.</em></p>" },
  { id:"lir", title:"The Children of Lir", category:"celtic", symbol:"\u2618", badge:"Celtic Mythology", short:"Four royal children cursed to live as swans for nine hundred years.", text:"<p>King Lir had four children he loved beyond all things. His second wife, Aoife, was consumed by jealousy. She took the children to a lake and struck them with a druid's wand, turning them into swans.</p><p>They would spend three hundred years on each of three lakes and seas, unable to return to human form. They kept their voices and their minds, and sang music so beautiful it could stop wars.</p><p>Nine hundred years later, when Christianity came to Ireland, the sound of a church bell broke the spell. The swans became human again, but ancient, withered, and dying. They were baptized before they passed.</p><p><em>Some curses carry within them a strange, terrible grace.</em></p>" },
  { id:"loki", title:"Loki's Punishment", category:"norse", symbol:"\u26a1", badge:"Norse Mythology", short:"The trickster god crossed the line and was bound beneath the earth to wait for the end.", text:"<p>Loki had always been the trickster, the chaos-bringer, the one who walked the line between friend and enemy. But when he engineered the death of Baldr, the most beloved of gods, the line was crossed.</p><p>The gods captured him. They bound him in a cave with the entrails of his own son, chains that no god could break. Above his face they placed a serpent that dripped venom onto his skin.</p><p>His wife Sigyn held a bowl above him to catch the drops. But when she had to empty it, the venom fell, and Loki's writhing caused earthquakes across the world.</p><p>He waits there still. And when he finally breaks free, it will be the beginning of Ragnarok.</p><p><em>Some debts are paid across eternity.</em></p>" },
  { id:"persephone", title:"Persephone's Descent", category:"greek", symbol:"\u2698", badge:"Greek Mythology", short:"Taken to the underworld by Hades, Persephone became its queen and gave the world its seasons.", text:"<p>She was picking flowers in a meadow when the earth split open and Hades rose in his black chariot. He took her to the underworld, and the world above fell into grief.</p><p>Her mother Demeter, goddess of the harvest, refused to let anything grow. Crops died. People starved. The gods begged Zeus to intervene.</p><p>Persephone was allowed to return, but she had eaten six pomegranate seeds in the underworld. For six months of every year, she must return to Hades as his queen.</p><p>Those six months are autumn and winter. When she returns to her mother, spring blooms. The world breathes again.</p><p><em>Even in the darkest place, something of you remains that belongs to the light.</em></p>" },
  { id:"change", title:"Chang'e and the Moon", category:"chinese", symbol:"\u6708", badge:"Chinese Mythology", short:"She drank the elixir of immortality and floated to the moon, watching the earth alone forever.", text:"<p>Her husband Hou Yi was a great archer who had shot down nine of the ten suns that once scorched the earth. As a reward, he was given the elixir of immortality.</p><p>Chang'e, fearing what immortality might do to her husband, drank it herself. She floated upward, past the clouds, past the stars, until she landed on the moon.</p><p>There she lives still, in the Moon Palace, with only a jade rabbit for company. On the night of the Mid-Autumn Festival, she is closest to the earth, and people leave offerings of mooncakes so she knows she is not forgotten.</p><p><em>Some sacrifices are made out of love. Some out of fear. The heart rarely knows which is which.</em></p>" },
  { id:"ra", title:"Ra's Journey Through Night", category:"egyptian", symbol:"\u2600", badge:"Egyptian Mythology", short:"Every night the sun god Ra battles the serpent Apophis to rise again at dawn.", text:"<p>Every evening, the sun god Ra stepped into his solar barque and began the twelve-hour journey through the Duat, the Egyptian underworld. Each hour was a different realm, each with its own dangers.</p><p>In the deepest hour, he faced Apophis, the serpent of chaos, a creature so vast it could swallow the entire sky. The gods aboard the barque fought it back with spears and magic.</p><p>Every night the battle was uncertain. Every morning, Ra emerged victorious, rising in the east as the sun, bringing light and life to the world once more.</p><p><em>The sun rises because someone, somewhere, still believes it will.</em></p>" },
  { id:"cuchulain", title:"Cuchulain: The Hound of Ulster", category:"celtic", symbol:"\u2694", badge:"Celtic Mythology", short:"Ireland's greatest warrior burned bright and fast, dying on his feet tied to a standing stone.", text:"<p>As a boy, Setanta killed the great hound of the smith Culann with his bare hands. To make amends, he offered to serve as the smith's guard dog until a replacement could be trained. From that day he was called Cu Chulainn.</p><p>He alone defended Ulster when all other warriors were struck down by a curse. For months he fought the armies of Connacht single-handedly, holding the ford, bleeding but never breaking.</p><p>He died standing up, tied to a standing stone so he would not fall, his enemies too afraid to approach until a raven landed on his shoulder and they knew he was gone.</p><p><em>Some people burn so bright that the world remembers the light long after the flame is out.</em></p>" },
  { id:"gilgamesh", title:"The Epic of Gilgamesh", category:"mesopotamian", symbol:"\u2605", badge:"Mesopotamian Mythology", short:"The oldest written story ever told. A king searches for immortality and finds something greater.", text:"<p>Gilgamesh was two-thirds god and one-third man, the greatest king of Uruk. He was arrogant and cruel until the gods created Enkidu, a wild man of the forest, to humble him.</p><p>They fought, became brothers, and together slew the Bull of Heaven and the monster Humbaba. But when Enkidu died, Gilgamesh was shattered. For the first time, he understood that he too would die.</p><p>He traveled to the ends of the earth seeking the secret of immortality. He found it, a plant at the bottom of the ocean, only to have it stolen by a serpent while he slept.</p><p>He returned to Uruk empty-handed. But he looked at the walls of his city, the walls he had built, and understood. His legacy was his immortality.</p><p><em>The greatest thing a man can leave behind is something that outlasts him.</em></p>" },
  { id:"quetzalcoatl", title:"Quetzalcoatl: The Feathered Serpent", category:"aztec", symbol:"\u1f40d", badge:"Aztec Mythology", short:"The feathered serpent god who created mankind and promised to return from the east.", text:"<p>Quetzalcoatl was the god of wind, air, and learning. He was depicted as a feathered serpent, a creature that united the earth and the sky, the mortal and the divine.</p><p>He taught mankind agriculture, mathematics, and the calendar. He opposed human sacrifice and demanded only butterflies and flowers as offerings.</p><p>His rival Tezcatlipoca tricked him into drunkenness and shame. Quetzalcoatl sailed away on a raft of serpents, promising to return from the east on a specific date to reclaim his throne.</p><p>When Hernan Cortes arrived from the east on that exact date in 1519, the Aztec emperor Moctezuma believed the prophecy had come true. The rest is history.</p><p><em>Prophecy is a door. It does not tell you who will walk through it.</em></p>" },
  { id:"shiva", title:"Shiva: The Destroyer and Creator", category:"hindu", symbol:"\u0950", badge:"Hindu Mythology", short:"The god of destruction who is also the god of creation, dancing the universe into existence.", text:"<p>Shiva is one of the three supreme gods of Hinduism. He is the destroyer, but destruction in Hindu thought is not evil. It is necessary. Without destruction, there can be no creation.</p><p>He performs the Tandava, the cosmic dance, and with each step the universe is destroyed and reborn. He sits in meditation on Mount Kailash, and his stillness holds the cosmos together.</p><p>He drank the poison Halahala that emerged from the churning of the cosmic ocean, holding it in his throat to save all creation. His throat turned blue, and he became Neelakantha, the Blue-Throated One.</p><p>He is the god of outcasts, wanderers, and those who do not fit. He welcomes all who come to him.</p><p><em>The one who destroys is also the one who makes space for something new.</em></p>" },
  { id:"amaterasu", title:"Amaterasu and the Cave", category:"japanese", symbol:"\u2600", badge:"Japanese Mythology", short:"The sun goddess hid in a cave and plunged the world into darkness until laughter brought her back.", text:"<p>Amaterasu, the goddess of the sun, was terrified by her brother Susanoo's violent rampages. She hid herself in a cave, and the world fell into total darkness. Crops died. Evil spirits roamed freely.</p><p>The eight million gods of Japan gathered outside the cave and tried everything to coax her out. Nothing worked.</p><p>Then the goddess Ame-no-Uzume began to dance, a wild, joyful, ridiculous dance. The gods burst into laughter. Amaterasu, curious about what could possibly be so funny in a world without light, peeked out.</p><p>The gods grabbed her and pulled her fully out of the cave. Light returned to the world. The sun rose again.</p><p><em>Sometimes the only thing that can end the darkness is laughter.</em></p>" }
];

var GODS = [
  { name:"Zeus", pantheon:"greek", role:"King of the Gods, God of Thunder", symbol:"\u26a1", desc:"Ruler of Mount Olympus. His lightning bolt could shatter mountains. Feared by gods and mortals alike, yet bound by the laws of fate." },
  { name:"Odin", pantheon:"norse", role:"Allfather, God of Wisdom", symbol:"\u16a8", desc:"He sacrificed his eye for wisdom and hung on the World Tree for nine days to learn the runes. He knows how the world ends and walks toward it anyway." },
  { name:"Ra", pantheon:"egyptian", role:"God of the Sun", symbol:"\u2600", desc:"The supreme deity of ancient Egypt. Every morning his solar barque rises in the east. Every night he battles chaos to rise again." },
  { name:"Amaterasu", pantheon:"japanese", role:"Goddess of the Sun", symbol:"\u2609", desc:"The great goddess of the sun and the universe in Shinto religion. The Imperial Family of Japan claims descent from her divine light." },
  { name:"Shiva", pantheon:"hindu", role:"The Destroyer and Transformer", symbol:"\u0950", desc:"One of the three supreme gods of Hinduism. His cosmic dance destroys the universe so it can be reborn. He is both terrifying and compassionate." },
  { name:"Thor", pantheon:"norse", role:"God of Thunder and Strength", symbol:"\u1f528", desc:"Son of Odin. His hammer Mjolnir could level mountains. He was the protector of mankind, always fighting the giants who threatened the world." },
  { name:"Anubis", pantheon:"egyptian", role:"God of the Dead", symbol:"\u2625", desc:"The jackal-headed god who weighed the hearts of the dead against a feather. If your heart was lighter than the feather, you entered paradise." },
  { name:"Athena", pantheon:"greek", role:"Goddess of Wisdom and War", symbol:"\u1f989", desc:"Born fully armored from the head of Zeus. She was the goddess of strategic warfare, wisdom, and crafts. Athens was named in her honor." },
  { name:"Loki", pantheon:"norse", role:"God of Mischief", symbol:"\u1f525", desc:"The trickster who walked the line between ally and enemy. His schemes saved the gods as often as they endangered them, until they didn't." },
  { name:"Isis", pantheon:"egyptian", role:"Goddess of Magic and Healing", symbol:"\u2640", desc:"The most powerful magician in the Egyptian pantheon. She reassembled her husband Osiris from fourteen pieces and breathed life back into him." },
  { name:"Susanoo", pantheon:"japanese", role:"God of Storms", symbol:"\u26c8", desc:"The storm god, brother of Amaterasu. Wild and unpredictable, he slew the eight-headed serpent Yamata no Orochi and found the legendary sword Kusanagi within its body." },
  { name:"Vishnu", pantheon:"hindu", role:"The Preserver", symbol:"\u1f4ab", desc:"One of the three supreme gods of Hinduism. He descends to earth in different forms whenever evil threatens to overwhelm good. His avatars include Rama and Krishna." }
];

var COMICS = [
  { id:"dragon", title:"Dragon Blood", meta:"Vol. 1 &bull; 12 Chapters &bull; Action / Myth", desc:"A half-dragon warrior seeks the truth of his bloodline across a world that fears him.", color:"rgba(139,26,26,0.5)", img:"https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&q=80", symbol:"\u40845" },
  { id:"oni", title:"Oni Rising", meta:"Vol. 1 &bull; 8 Chapters &bull; Dark / Horror", desc:"An Oni cast out from the demon realm must survive in the human world without losing his soul.", color:"rgba(30,20,80,0.6)", img:"https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=400&q=80", symbol:"\u9b3c" },
  { id:"moon", title:"Moon Goddess", meta:"Vol. 1 &bull; 10 Chapters &bull; Romance / Spiritual", desc:"Chang'e descends from the moon for one night every century. This time, she stays longer than she should.", color:"rgba(20,60,80,0.6)", img:"https://images.unsplash.com/photo-1532693322450-2cb5c511067d?w=400&q=80", symbol:"\u6708" },
  { id:"zeus", title:"Fall of Olympus", meta:"Vol. 1 &bull; 15 Chapters &bull; War / Epic", desc:"The gods of Olympus are dying one by one. A mortal girl is the only one who knows why.", color:"rgba(80,60,10,0.6)", img:"https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80", symbol:"\u26a1" },
  { id:"fenrir", title:"Fenrir's Chain", meta:"Vol. 1 &bull; 9 Chapters &bull; Norse / Action", desc:"The great wolf Fenrir breaks free centuries before Ragnarok. The gods scramble to stop what cannot be stopped.", color:"rgba(40,10,10,0.7)", img:"https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=400&q=80", symbol:"\u2694" },
  { id:"samurai", title:"Last Samurai of the Gods", meta:"Vol. 1 &bull; 11 Chapters &bull; Samurai / Spiritual", desc:"A samurai who cannot die wanders feudal Japan, carrying a sword that holds the soul of a fallen god.", color:"rgba(10,40,20,0.6)", img:"https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=400&q=80", symbol:"\u4f8d" }
];

var FACTS = [
  "The Great Pyramid of Giza is the only one of the Seven Wonders of the Ancient World still standing.",
  "The Norse believed the world was created from the body of a giant named Ymir.",
  "Ancient Egyptians believed the heart, not the brain, was the seat of intelligence and emotion.",
  "The word 'chaos' comes from the Greek word for the void that existed before creation.",
  "In Japanese mythology, there are said to be eight million gods, called Kami.",
  "The Aztec calendar was more accurate than the European calendar of the same era.",
  "Homer's Iliad and Odyssey were composed around 800 BCE and are still read today.",
  "The Epic of Gilgamesh, written in 2100 BCE, contains a flood story remarkably similar to Noah's Ark.",
  "Ancient Greeks believed that dreams were messages sent by the gods.",
  "The Hindu god Vishnu has ten avatars, or earthly forms, including a fish, a turtle, and a boar.",
  "Norse Vikings believed that warriors who died in battle went to Valhalla to feast with Odin.",
  "The Sphinx of Giza is estimated to be over 4,500 years old.",
  "In Celtic mythology, the Otherworld exists alongside our world, invisible but always present.",
  "The word 'volcano' comes from Vulcan, the Roman god of fire.",
  "Ancient Mesopotamians invented the concept of writing around 3400 BCE."
];